FROM node:20-alpine

WORKDIR /app
RUN chown node:node /app
USER node

COPY --chown=node:node package.json package-lock.json ./
RUN npm install

COPY --chown=node:node app ./app
COPY --chown=node:node components ./components
COPY --chown=node:node lib ./lib
COPY --chown=node:node public ./public
COPY --chown=node:node next-env.d.ts next.config.mjs postcss.config.js tailwind.config.ts tsconfig.json ./
RUN npm run build

EXPOSE 3000
CMD ["npm", "start"]
