name: backend-ci

on:
  push:
    branches: [main, master]
    tags: ["v*.*.*"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-cov

      - name: Ensure bcrypt/passlib pins
        run: |
          pip install "bcrypt==4.0.1" "passlib>=1.7.4"

      - name: Prepare OUTPUTS_DIR
        run: |
          mkdir -p "$RUNNER_TEMP/outputs"
          echo "OUTPUTS_DIR=$RUNNER_TEMP/outputs" >> "$GITHUB_ENV"

      - name: Lint (flake8)
        run: flake8

      - name: Run tests (pytest with coverage)
        run: pytest --cov=app --cov-report=term-missing --cov-fail-under=85
