name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install html5validator
        run: |
          python -m pip install --upgrade pip
          pip install html5validator
      - name: Validate HTML files
        run: |
          find . -name "*.html" \
            -not -path "./.git/*" \
            -not -path "./apps/frontend/node_modules/*" \
            -not -path "./apps/frontend/dist/*" \
            -print0 | xargs -0 -I{} bash -c "echo Validating {}; html5validator --alsocheckcss --filterurl https?://.* --root . --match {}"

  link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lychee link checker
        uses: lycheeverse/lychee-action@v2
        with:
          args: --verbose --no-progress --exclude-path "apps/frontend/node_modules/**,apps/frontend/dist/**" .
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  frontend-lint:
    if: ${{ hashFiles('apps/frontend/package.json') != '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install deps
        run: |
          cd apps/frontend
          npm ci || npm install
      - name: Lint (ESLint)
        run: |
          cd apps/frontend
          npm run lint

