permissions:
  contents: read
  checks: write
  pull-requests: write
  statuses: write

name: CI

on:
  pull_request:
    branches: [main]
  workflow_dispatch: {}

jobs:
  validate-html:
    if: ${{ github.event_name != 'push' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install html5validator
        run: |
          python -m pip install --upgrade pip
          pip install html5validator
      - name: Validate HTML files
        continue-on-error: true
        run: |
          # Limit validation to site/ to avoid scanning non-web assets
          find site -type f -name "*.html" -print0 | xargs -0 -I{} bash -c "echo Validating {}; html5validator --alsocheckcss --filterurl https?://.* --root site --match {}"

  link-check:
    if: ${{ github.event_name != 'push' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lychee link checker
        continue-on-error: true
        uses: lycheeverse/lychee-action@v2
        with:
          args: >-
            --verbose --no-progress 
            --exclude-path "apps/frontend/node_modules/**,apps/frontend/dist/**" 
            --exclude "https://cdn.jsdelivr.net/.*"  --exclude "https://maths.labomaths.tn/.*" 
            --accept 200,206,301,302,303,307,308,429 
            --timeout 20 --retry-wait-time 2 --max-redirects 5 --max-retries 2 
            site/
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  frontend-lint:
    if: ${{ github.event_name != 'push' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Detect frontend workspace
        id: detect
        shell: bash
        run: |
          if [ -f "apps/frontend/package.json" ]; then echo "present=true" >> "$GITHUB_OUTPUT"; else echo "present=false" >> "$GITHUB_OUTPUT"; fi
      - name: Setup Node
        if: ${{ steps.detect.outputs.present == 'true' }}
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install deps
        if: ${{ steps.detect.outputs.present == 'true' }}
        run: |
          cd apps/frontend
          npm ci || npm install
      - name: Lint (ESLint)
        if: ${{ steps.detect.outputs.present == 'true' }}
        run: |
          cd apps/frontend
          npm run lint
