name: Deploy to VPS

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

concurrency:
  group: deploy-vps-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies (rsync, ssh-client, jq)
        run: |
          sudo apt-get update -y
          sudo apt-get install -y rsync openssh-client jq

      - name: Start ssh-agent and add key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add VPS host to known_hosts
        env:
          VPS_HOST: ${{ secrets.VPS_HOST }}
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "$VPS_HOST" >> ~/.ssh/known_hosts

      - name: Wait for CI workflows success (CI and backend-ci)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          REPO="${GITHUB_REPOSITORY}"
          SHA="${GITHUB_SHA}"
          WF1="CI"
          WF2="backend-ci"
          echo "Waiting for workflows '$WF1' and '$WF2' on $SHA ..."
          for i in $(seq 1 60); do
            json=$(curl -sSf -H "Authorization: Bearer $GITHUB_TOKEN" -H "Accept: application/vnd.github+json" \
              "$GITHUB_API_URL/repos/$REPO/actions/runs?head_sha=$SHA&per_page=100")
            c1=$(echo "$json" | jq -r --arg n "$WF1" '.workflow_runs[] | select(.name==$n) | .conclusion' | head -n1)
            c2=$(echo "$json" | jq -r --arg n "$WF2" '.workflow_runs[] | select(.name==$n) | .conclusion' | head -n1)
            s1=$(echo "$json" | jq -r --arg n "$WF1" '.workflow_runs[] | select(.name==$n) | .status' | head -n1)
            s2=$(echo "$json" | jq -r --arg n "$WF2" '.workflow_runs[] | select(.name==$n) | .status' | head -n1)
            if [ "$c1" = "success" ] && [ "$c2" = "success" ]; then
              echo "Both workflows succeeded."
              exit 0
            fi
            if [ "$c1" = "failure" ] || [ "$c1" = "cancelled" ] || [ "$c2" = "failure" ] || [ "$c2" = "cancelled" ]; then
              echo "CI failed (CI:$c1, backend-ci:$c2). Aborting deploy."
              exit 1
            fi
            echo "CI in progress... (CI: $s1/$c1, backend-ci: $s2/$c2). Attempt $i/60"
            sleep 10
          done
          echo "Timeout waiting for CI."
          exit 1

      - name: Deploy static site (docs/ -> webroot) via rsync
        env:
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_PATH: ${{ secrets.VPS_PATH }}
        run: |
          set -euo pipefail
          test -n "$VPS_HOST" && test -n "$VPS_USER" && test -n "$VPS_PATH" || { echo "Secrets VPS_HOST/VPS_USER/VPS_PATH manquants"; exit 1; }
          # Publish the contents of docs/ directly into the webroot
          rsync -az --delete --human-readable --progress \
            docs/ "$VPS_USER@$VPS_HOST:$VPS_PATH/"

      - name: Sanity check (VPS endpoints)
        env:
          VPS_BASE_URL: ${{ secrets.VPS_BASE_URL }}
        run: |
          set -euo pipefail
          if [ -z "${VPS_BASE_URL:-}" ]; then
            echo "VPS_BASE_URL not set, skipping VPS sanity checks."
            exit 0
          fi
          check_url() {
            url="$1"
            for i in $(seq 1 12); do
              code=$(curl -s -o /dev/null -w "%{http_code}" -L "$url" || true)
              if [ "$code" = "200" ]; then
                echo "OK $url"
                return 0
              fi
              echo "Attempt $i/12: $code $url"
              sleep 10
            done
            echo "FAIL $url"
            return 1
          }
          check_url "$VPS_BASE_URL/"
          check_url "$VPS_BASE_URL/EDS_premiere/Calcul_litteral/fiche_exercices_calcul_litteral_premiere.html"
          check_url "$VPS_BASE_URL/EDS_terminale/Suites/fiche_eleve_suites_rappels_premiere.html"

      - name: Sanity check (GitHub Pages endpoints)
        continue-on-error: true
        run: |
          set -euo pipefail
          owner="${GITHUB_REPOSITORY%%/*}"
          repo="${GITHUB_REPOSITORY##*/}"
          base="https://${owner}.github.io/${repo}"
          check_url() {
            url="$1"
            for i in $(seq 1 12); do
              code=$(curl -s -o /dev/null -w "%{http_code}" -L "$url" || true)
              if [ "$code" = "200" ]; then
                echo "OK $url"
                return 0
              fi
              echo "Attempt $i/12: $code $url"
              sleep 10
            done
            echo "FAIL $url"
            return 1
          }
          check_url "$base/"
          check_url "$base/EDS_premiere/Calcul_litteral/fiche_exercices_calcul_litteral_premiere.html"
          check_url "$base/EDS_terminale/Suites/fiche_eleve_suites_rappels_premiere.html"

