name: Deploy to VPS

on:
  push:
    branches: [ main ]
    paths:
      - 'EDS_premiere/**'
      - 'EDS_terminale/**'
      - 'Maths_expertes/**'
      - 'docs/**'
      - '.github/workflows/deploy.yml'
      - 'README.md'
      - 'CHANGELOG.md'
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install rsync and ssh-client
        run: |
          sudo apt-get update -y
          sudo apt-get install -y rsync openssh-client

      - name: Start ssh-agent and add key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add VPS host to known_hosts
        env:
          VPS_HOST: ${{ secrets.VPS_HOST }}
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "$VPS_HOST" >> ~/.ssh/known_hosts

      - name: Deploy static site (EDS + docs) via rsync
        env:
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_PATH: ${{ secrets.VPS_PATH }}
        run: |
          test -n "$VPS_HOST" && test -n "$VPS_USER" && test -n "$VPS_PATH" || { echo "Secrets VPS_HOST/VPS_USER/VPS_PATH manquants"; exit 1; }
          rsync -az --delete --human-readable --progress \
            EDS_premiere EDS_terminale Maths_expertes docs index.html \
            "$VPS_USER@$VPS_HOST:$VPS_PATH/"

