name: frontend-audit

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch: {}

jobs:
  npm-audit:
    if: ${{ github.event_name != 'push' && hashFiles('apps/frontend/package.json') != '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install deps
        run: |
          cd apps/frontend
          npm ci || npm install
      - name: npm audit (fail on high/critical)
        run: |
          cd apps/frontend
          npm audit --audit-level=high

