name: Front CI – Playwright + Lighthouse

on:
  pull_request:
    branches: [ "**" ]
  push:
    branches: [ "**" ]

concurrency:
  group: front-${{ github.ref }}
  cancel-in-progress: true

jobs:
  front-checks:
    name: Front – UI tests then Lighthouse
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: site

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: "site/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Build (Vite)
        run: npm run build

      - name: Start preview server (Vite)
        run: |
          nohup npm run preview -- --host --port 4173 >/dev/null 2>&1 &
          npx wait-on http://127.0.0.1:4173

      - name: Run Playwright tests (UI)
        env:
          BASE_URL: "http://127.0.0.1:4173"
        run: npx playwright test --reporter=line

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: site/playwright-report/
          if-no-files-found: ignore

      - name: Upload Playwright screenshots & traces
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-artifacts
          path: |
            site/test-results/
            site/playwright-report/
          if-no-files-found: ignore

      - name: Install Lighthouse CI CLI
        run: npm i -D @lhci/cli wait-on

      - name: Run Lighthouse CI (assert budgets)
        working-directory: ..
        run: |
          npx wait-on http://127.0.0.1:4173
          npx lhci autorun --config=.lighthouserc.json

      - name: Upload Lighthouse reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-reports
          path: ../.lhci_reports
          if-no-files-found: ignore
