name: frontend-audit

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch: {}

jobs:
  npm-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Detect frontend workspace
        id: detect
        shell: bash
        run: |
          if [ -f "apps/frontend/package.json" ]; then echo "present=true" >> "$GITHUB_OUTPUT"; else echo "present=false" >> "$GITHUB_OUTPUT"; fi
      - name: Setup Node
        if: ${{ steps.detect.outputs.present == 'true' }}
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install deps
        if: ${{ steps.detect.outputs.present == 'true' }}
        run: |
          cd apps/frontend
          npm ci || npm install
      - name: npm audit (fail on high/critical)
        if: ${{ steps.detect.outputs.present == 'true' }}
        run: |
          cd apps/frontend
          npm audit --audit-level=high

