name: Uptime monitor
on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch: {}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check VPS (if VPS_BASE_URL provided)
        if: ${{ secrets.VPS_BASE_URL != '' }}
        shell: bash
        env:
          BASE: ${{ secrets.VPS_BASE_URL }}
        run: |
          set -euo pipefail
          base="${BASE%/}"
          for path in "/" "/sitemap.xml"; do
            code=$(curl -s -o /dev/null -w '%{http_code}' -L "$base$path" || true)
            echo "$base$path -> $code"
            if [ "$code" != "200" ]; then
              echo "Endpoint failed: $base$path ($code)"; exit 1
            fi
          done

      - name: Check GitHub Pages (best-effort)
        shell: bash
        run: |
          set -euo pipefail
          owner="${GITHUB_REPOSITORY%%/*}"
          repo="${GITHUB_REPOSITORY##*/}"
          base="https://${owner}.github.io/${repo}"
          for path in "/" "/sitemap.xml" "/robots.txt"; do
            code=$(curl -s -o /dev/null -w '%{http_code}' -L "$base$path" || true)
            echo "$base$path -> $code"
          done
