name: Backend tests

on:
  push:
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r apps/backend/requirements.txt
          pip install pytest-cov
      - name: Run pytest
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          pytest apps/backend/ --cov=apps.backend.app --maxfail=1 --disable-warnings -q

